services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./bd.sql:/docker-entrypoint-initdb.d/bd.sql
    networks:
      - enduran
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  user-info:
    build:
      context: ./user-info
      dockerfile: Dockerfile
    volumes:
      - ./user-info/config/config.yaml:/app/config/config.yaml
    ports:
      - "8081:8080"
    networks:
      - enduran
    depends_on:
      postgres:
        condition: service_healthy

  training:
    build:
      context: ./end-trainings
      dockerfile: Dockerfile
    volumes:
      - ./end-trainings/config/config.yaml:/app/config/config.yaml
    ports:
      - "8080:8080"
    networks:
      - enduran
    depends_on:
      postgres:
        condition: service_healthy

  auth:
    build:
      context: ./end-auth
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - enduran
    volumes:
      - ./end-auth/config/config.yaml:/app/config/config.yaml
    ports:
      - "8082:8082"

networks:
  enduran:
    driver: bridge