version: '3.8'

services:
  user-info:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config/config.yaml:/app/config/config.yaml
    ports:
      - "8081:8080"
    networks:
      - pg-db
    depends_on:
      postgres:
        condition: service_healthy  

  postgres:
    image: postgres:15-alpine
    container_name: user_info_db
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - ./bd.sql:/docker-entrypoint-initdb.d/bd.sql
    networks:
      - pg-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  pg-db:
    driver: bridge